export const ratesUpdatedAt = new Date().toISOString();

export const FD_RATES = [
  {
    id: 'suryoday-1',
    bank: 'Suryoday Small Finance Bank',
    bankShort: 'Suryoday SFB',
    tenure: '12 months',
    tenureMonths: 12,
    rate: 9.10,
    minAmount: 5000,
    seniorRate: 9.60,
    type: 'Small Finance Bank',
    safetyRating: 'AA-',
    insured: true,
    highlight: true,
  },
  {
    id: 'esaf-1',
    bank: 'ESAF Small Finance Bank',
    bankShort: 'ESAF SFB',
    tenure: '24 months',
    tenureMonths: 24,
    rate: 8.75,
    minAmount: 1000,
    seniorRate: 9.25,
    type: 'Small Finance Bank',
    safetyRating: 'AA-',
    insured: true,
    highlight: false,
  },
  {
    id: 'ujjivan-1',
    bank: 'Ujjivan Small Finance Bank',
    bankShort: 'Ujjivan SFB',
    tenure: '18 months',
    tenureMonths: 18,
    rate: 8.50,
    minAmount: 1000,
    seniorRate: 9.00,
    type: 'Small Finance Bank',
    safetyRating: 'AA',
    insured: true,
    highlight: false,
  },
  {
    id: 'jana-1',
    bank: 'Jana Small Finance Bank',
    bankShort: 'Jana SFB',
    tenure: '36 months',
    tenureMonths: 36,
    rate: 8.25,
    minAmount: 5000,
    seniorRate: 8.75,
    type: 'Small Finance Bank',
    safetyRating: 'BBB+',
    insured: true,
    highlight: false,
  },
  {
    id: 'utkarsh-1',
    bank: 'Utkarsh Small Finance Bank',
    bankShort: 'Utkarsh SFB',
    tenure: '12 months',
    tenureMonths: 12,
    rate: 8.50,
    minAmount: 1000,
    seniorRate: 9.00,
    type: 'Small Finance Bank',
    safetyRating: 'A+',
    insured: true,
    highlight: false,
  },
  {
    id: 'shriram-1',
    bank: 'Shriram Finance',
    bankShort: 'Shriram Fin.',
    tenure: '24 months',
    tenureMonths: 24,
    rate: 8.18,
    minAmount: 5000,
    seniorRate: 8.68,
    type: 'NBFC',
    safetyRating: 'AAA',
    insured: false,
    highlight: false,
  },
  {
    id: 'mahindra-1',
    bank: 'Mahindra Finance',
    bankShort: 'Mahindra Fin.',
    tenure: '36 months',
    tenureMonths: 36,
    rate: 8.05,
    minAmount: 10000,
    seniorRate: 8.55,
    type: 'NBFC',
    safetyRating: 'AAA',
    insured: false,
    highlight: false,
  },
  {
    id: 'sbi-1',
    bank: 'State Bank of India',
    bankShort: 'SBI',
    tenure: '12 months',
    tenureMonths: 12,
    rate: 6.80,
    minAmount: 1000,
    seniorRate: 7.30,
    type: 'PSU Bank',
    safetyRating: 'AAA',
    insured: true,
    highlight: false,
  },
];
